#define  QUITSUR		"Opravdu chcete skoncit\n"\
					"tento skvely herni zazitok?"

#define  CURGAME		"Prave hrajete hru.\n"\
					"Pokud budete pokracovat,\n"\
					"stara hra bude smazana. OK?"

#define  GAMESVD	"Na teto pozici jiz\n"\
				  "existuje ulozena hra.\n"\
				  "Prepsat?"

#define  ENDGAMESTR	"Opravdu chcete ukoncit\n"\
					"probiha jici hru?\n"\
					"           (A nebo N):"

#define   STR_NG	"Nova hra"
#define   STR_SD	"Zvuk"
#define   STR_CL	"Ovladani"
#define   STR_LG	"Nacist hru"
#define   STR_SG	"Ulozit hru"
#define   STR_CV	"Zmenit pohled"
#define   STR_VS	"Nejlepsi skore"
#define   STR_EG	"Ukoncit hru"
#define   STR_BD	"Zpet do dema"
#define   STR_QT	"Konec"

#define   STR_LOADING	"Nacitam"
#define   STR_SAVING	"Ukladam"

#define   STR_GAME	"Zpet do hry"
#define   STR_DEMO	"Zpet do dema"
#define   STR_LGC		"Nacitam hru nazvanou\n\""
#define   STR_EMPTY	"prazdne"
#define   STR_CALIB	"Kalibrovat"
#define   STR_JOYST	"Joystick"
#define   STR_MOVEJOY	"Pohybte joystickem\n"\
						"vlevo nahoru a\n"\
						"stisknete tlacitko 0\n"
#define   STR_MOVEJOY2	"Pohybte joystickem\n"\
						"vpravo dolu a\n"\
						"stisknete tlacitko 1\n"
#define   STR_ESCEXIT	"ESC pro ukonceni"
#define   STR_NONE	"Zadny"
#define   STR_PC		"PC Reproduktor"
#define   STR_ALSB	"AdLib/Sound Blaster"
#define   STR_DISNEY	"Disney Sound Source"
#define   STR_SB		"Sound Blaster"

#define   STR_MOUSEEN	"Mys povolena"
#define   STR_JOYEN	"Joystick povolen"
#define   STR_PORT2	"Pouzit joystick port 2"
#define   STR_GAMEPAD	"Gravis GamePad povolen"
#define   STR_SENS	"Citlivost mysi"
#define   STR_CUSTOM	"Nastavit ovladace"

#define   STR_DADDY	"Muzu hrat, tatinku?"
#define   STR_HURTME	"Netrestej me."
#define   STR_BRINGEM	"Posli je na mne!"
#define   STR_DEATH	"Jsem sama smrt!"

#define   STR_MOUSEADJ	"Nastavit citlivost mysi"
#define   STR_SLOW	"Pomalu"
#define   STR_FAST	"Rychle"

#define   STR_CRUN	"Behat"
#define   STR_COPEN	"Otevrit"
#define   STR_CFIRE	"Strelit"
#define   STR_CSTRAFE	"Strafovat"

#define   STR_LEFT	"Vlevo"
#define   STR_RIGHT	"Vpravo"
#define   STR_FRWD	"Vpred"
#define   STR_BKWD	"Vzad"
#define   STR_THINK	"Myslim"

#define   STR_SIZE1	"Sipkami zmente velikost"
#define   STR_SIZE2	"ENTER pro potvrzeni"
#define   STR_SIZE3	"ESC pro zruseni"

#define   STR_YOUWIN	"vyhral jsi!"

#define   STR_TOTALTIME	"celkovy cas"

#define   STR_RATKILL		"zabiti    %"
#define   STR_RATSECRET		"tajemstvi    %"
#define   STR_RATTREASURE	"poklady    %"

#define   STR_BONUS	"bonus"
#define   STR_TIME	"cas"
#define   STR_PAR	" par"

#define   STR_RAT2KILL		"pocet zabiti    %"
#define   STR_RAT2SECRET	"pocet tajemstvi    %"
#define   STR_RAT2TREASURE	"pocet pokladu    %"

#define   STR_DEFEATED	"porazen!"

#define   STR_CHEATER1	"Nyni mas 100% zdravi,"
#define   STR_CHEATER2	"99 naboju a oba klice!"
#define   STR_CHEATER3	"Vezmi na vedomi, ze jsi"
#define   STR_CHEATER4	"znicil sve sance na"
#define   STR_CHEATER5	"nejlepsi skore!"

#define   STR_NOSPACE1	"Na disku neni dostatek"
#define   STR_NOSPACE2	"mista pro ulozeni hry!"

#define   STR_SAVECHT1	"Tvuj soubor ulozene hry"
#define   STR_SAVECHT2	"je, reknu ti to rovne, \"poskozeny\"."
#define   STR_SAVECHT3	"Ale nechavam te hrat"
#define   STR_SAVECHT4	"i tak...."

#define   STR_SEEAGAIN	"Zobrazit znovu!"
