name: Compile Wolfenstein 3D

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup DosBox
      run: sudo apt-get install dosbox

    - name: Download and Extract Borland C++
      run: |
        mkdir -p ${{github.workspace}}/tools
        curl -L -o ${{github.workspace}}/tools/borland.zip http://fabiensanglard.net/Compile_Like_Its_1992/tools/BCPP31.zip
        unzip ${{github.workspace}}/tools/borland.zip -d ${{github.workspace}}/tools/borland

    - name: Prepare Borland C++ Setup Script
      run: |
        echo 'mount c ${{github.workspace}}' > ${{github.workspace}}/dosbox_install.conf
        echo 'c:' >> ${{github.workspace}}/dosbox_install.conf
        echo 'cd tools/borland' >> ${{github.workspace}}/dosbox_install.conf
        echo 'install.exe' >> ${{github.workspace}}/dosbox_install.conf
        echo '[log]' >> ${{github.workspace}}/dosbox.conf
        echo 'logfile=install_log.txt' >> ${{github.workspace}}/dosbox.conf

    - name: Automate Borland C++ Installation
      run: |
        export TERM=dumb
        (echo "ENTER"; echo "ENTER"; echo "C"; echo "\BCSETUP"; echo "ENTER"; echo "ENTER"; echo "ENTER"; echo "N") | dosbox -noconsole -conf ${{github.workspace}}/dosbox_install.conf
        cat install_log.txt

    - name: Prepare Build Script
      run: |
        echo 'mount c ${{github.workspace}}' > ${{github.workspace}}/dosbox_build.conf
        echo 'c:' >> ${{github.workspace}}/dosbox_build.conf
        echo 'cd WOLF3D/SRC' >> ${{github.workspace}}/dosbox_build.conf
        echo 'bcc +WOLF3D.CFG' >> ${{github.workspace}}/dosbox_build.conf
        echo '[log]' >> ${{github.workspace}}/dosbox_build.conf
        echo 'logfile=build_log.txt' >> ${{github.workspace}}/dosbox_build.conf

    - name: Compile Wolfenstein 3D
      run: |
        export TERM=dumb
        dosbox -noconsole -conf ${{github.workspace}}/dosbox_build.conf
        cat build_log.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-game
        path: |
          ${{github.workspace}}/WOLF3D/SRC/*.EXE
          ${{github.workspace}}/WOLF3D/SRC/*.MAP
