---
name: Build Wolfenstein 3D
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dosbox
        run: |
          sudo apt-get install snapd
          sudo snap install dosbox-x
      - name: Run DosBox to build Wolf3D
        run: >
          export TERM=dumb

          dosbox-x -silent -debug -conf dosbox.conf -c "mount c . && c: && call autoexec.bat" -log-con 
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-dos
          path: WOLF3D
      - name: Upload console log
        uses: actions/upload-artifact@v3
        with:
          name: dosbox-console-log
          path: dosbox_console_log.txt
  generate-html:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-dos
          path: ./artifact

      - name: List files in artifact directory
        run: ls -R ./artifact
          
      - name: Base64 encode the build output
        run: |
          base64 ./artifact/wolf3d.zip > wolf3d_base64.txt
      - name: Generate HTML file
        run: >
          echo "<!DOCTYPE html>

          <html>

          <head>
              <title>Wolfenstein 3D</title>
              <script src='https://js-dos.com/6.22/js-dos.js'></script>
          </head>

          <body>
              <h1>Wolfenstein 3D</h1>
              <div id='jsdos'></div>
              <script>
                  async function initDosBox() {
                      const response = await fetch('data:application/zip;base64,$(cat wolf3d_base64.txt)');
                      const blob = await response.blob();
                      const dosbox = await Dos(document.getElementById('jsdos')).run(blob);
                      dosbox.onrun = (ci) => {
                          ci.simulateKeyPress(13); // Press Enter to skip intro
                      };
                  }
                  initDosBox();
              </script>
          </body>

          </html>" > wolf3d.html
      - name: Upload HTML file
        uses: actions/upload-artifact@v3
        with:
          name: wolf3d-html
          path: wolf3d.html
