name: Compile Wolfenstein 3D

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup DosBox
      run: sudo apt-get install dosbox

    - name: Prepare Build Script
      run: |
        echo 'mount c ${{github.workspace}}' > ${{github.workspace}}/dosbox_build.conf
        echo 'c:' >> ${{github.workspace}}/dosbox_build.conf
        echo 'cd WOLFSRC' >> ${{github.workspace}}/dosbox_build.conf
        echo 'bcc @wolf3d.prj' >> ${{github.workspace}}/dosbox_build.conf
        echo 'exit' >> ${{github.workspace}}/dosbox_build.conf

    - name: Compile Wolfenstein 3D
      run: |
        export TERM=dumb
        dosbox -noconsole -conf ${{github.workspace}}/dosbox_build.conf
        cat build_log.txt

    - name: Zip the Output
      run: |
        zip -r wolf3d.zip WOLF3D

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-game
        path: |
          wolf3d.zip
