name: Build Wolfenstein 3D

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dosbox-x (apt)
      run: sudo apt-get install -y dosbox

    - name: Prepare Assets
      run: |
        # Create build directory
        mkdir build
        # Generate assets batch file
        echo 'echo Preparing assets...' > build/assets.bat

    - name: Compile
      uses: joncloud/dos-build-action@main
      timeout-minutes: 2
      with:
        programs: |
          $/borlandc:c:\borlandc
          WOLFSRC:c:\WOLFSRC
          WOLF3D:c:\WOLF3D
        run: |
          c:
          cd \WOLFSRC
          bcc @wolf3d.prj > c:\build\build_log.txt
          c:\build\assets.bat
        conf: |
          [dosbox]
          memsize=256

          [cpu]
          cycles=max
          turbo=true

    - name: Prepare Results
      if: always()
      run: |
        echo "Build Log"
        cat build/build_log.txt

        rm build/build_log.txt

    - name: Zip the build output
      run: |
        zip -r wolf3d.zip WOLF3D

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-dos
        path: wolf3d.zip
