name: Build Wolfenstein 3D

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dosbox-x (apt)
      run: sudo apt-get install -y dosbox

    - name: Prepare DosBox build configuration
      run: |
        echo '[autoexec]' > dosbox_build.conf
        echo 'mount c ${{ github.workspace }}' >> dosbox_build.conf
        echo 'c:' >> dosbox_build.conf
        echo 'cd WOLFSRC' >> dosbox_build.conf
        echo 'bcc @wolf3d.prj' >> dosbox_build.conf
        echo 'exit' >> dosbox_build.conf

    - name: Compile with DosBox
      run: dosbox -noconsole -conf dosbox_build.conf

    - name: Prepare Results
      if: always()
      run: |
        echo "Build Log"
        cat build/*.txt
        rm build/*.txt

    - name: Zip the build output
      run: |
        zip -r wolf3d.zip WOLF3D

    - uses: actions/upload-artifact@v3
      with:
        name: build-dos
        path: wolf3d.zip
