name: Build Wolfenstein 3D

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dosbox
      run: |
        sudo apt-get install snapd
        sudo snap install dosbox-x

    - name: Run DosBox to build Wolf3D
      run: |
        export TERM=dumb
        dosbox-x -early-debug -silent -conf dosbox.conf -c "mount c . && c: && call autoexec.bat"

    - name: Zip the build output
      run: |
        zip -r wolf3d.zip WOLF3D

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-dos
        path: wolf3d.zip
