name: Build Wolfenstein 3D

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dosbox
      run: |
        sudo apt-get install snapd
        sudo snap install dosbox-x

    - name: Run DosBox to build Wolf3D
      run: |
        export TERM=dumb
        dosbox-x -silent -debug -conf dosbox.conf -c "mount c . && c: && call autoexec.bat" -log-con 

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-dos
        path: WOLF3D

    - name: Upload console log
      uses: actions/upload-artifact@v3
      with:
        name: dosbox-console-log
        path: dosbox_console_log.txt
